version: '3.8'

services:
  facefusion.v2:
    container_name: facefusion-nvidia-docker
    image: nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu24.04
    restart: always
    build:
      context: .
      args:
        FACEFUSION_VERSION: "2.0.0"
    ports:
      - "7862:7860"
    volumes:
      - facefusion_v2_data:/home/appuser/facefusion
    mem_reservation: "256M"
    mem_limit: "8G"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['all']
              capabilities: [ gpu, video ]

volumes:
  facefusion_v2_data:
    external: true
