version: '3.8'

services:
  kohya_ss:
    container_name: kohya_ss-nvidia-docker
    image: nvidia/cuda:12.2.2-cudnn8-runtime-ubuntu24.04
    restart: always
    build:
      context: ./kohya_ss/
    ports:
      - "7861:7860"
    volumes:
      - kohya_ss:/home/appuser/kohya_ss
      - /tmp/.X11-unix:/tmp/.X11-unix
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['all']
              capabilities: [gpu]
